database:
  mysql:
    addr:
    port: 3306
    username: "root"
    password: "zhaoxijun7"
    db-name: "QAcommunity"
  redis:
    addr:
    port: 6379


logger:
  max-size: 10
  max-groups: 20
  max-age: 30
  log-type: "console"
  save-path: "log"

auth:
  jwt:
    expires-time: 604800
    secret-key: "dODNfSD821dd%%3vdh8"

